### ISSUE TITLE
Source mac address of all packets become same 

### ISSUE THREAD

**Issue by michaelc168** [H21lab/json2pcap#1] opened 2018-08-07 06:25 UTC
Converting from .pcap to .json and then back to .pcap without touching, although file size remain exactly same, but the source mac of all packets all became '00:a0:20:08:00:00', while destination mac address all became '00:00:24:00:24:40'?

**Comment by H21lab** [comment] 2020-06-01 10:32
I do not observe this behavior. As the issue is old I will close it. If needed, please reopen it and attach pcap to reproduce the problem.

**Closed as completed by H21lab** 2020-06-01 10:32 UTC
